/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GOffertaP.java
 *
 * Created on 9-lug-2011, 16.42.44
 */
package app.gui;

import app.Main;
import archive.data.Corso;
import archive.data.Settimana;
import archive.exception.DoubleRoomFullException;
import archive.exception.SingleRoomFullException;
import archive.system.AgenziaSystem;
import archive.system.OfferManager;
import java.io.FileNotFoundException;
import javax.swing.*;

public class GOffertaP extends javax.swing.JFrame {

    private OfferManager offermanager = new OfferManager(true);
    

    /** Creates new form GOffertaP */
    public GOffertaP() {
        Main.gui.setVisible(false);
        initComponents();
        jBnsdInc.setVisible(false);
        jBnsdDec.setVisible(false);
        jBnsuInc.setVisible(false);
        jBnsuDec.setVisible(false);
        jBConferma.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jCBV.setVisible(false);
        jCBE.setVisible(false);
        jCBT.setVisible(false);
        jCBS.setVisible(false);
        jCBB.setVisible(false);
        jCmBElenco.setVisible(false);
        jFTFNsett.setVisible(false);
        jFTFNsd.setVisible(false);
        jFTFPsd.setVisible(false);
        jFTFNsu.setVisible(false);
        jFTFPsu.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCmBElenco = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jFTFNsett = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFTFNsd = new javax.swing.JFormattedTextField();
        jBnsdInc = new javax.swing.JButton();
        jBnsdDec = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFTFPsd = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFTFNsu = new javax.swing.JFormattedTextField();
        jBnsuInc = new javax.swing.JButton();
        jBnsuDec = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jFTFPsu = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jCBV = new javax.swing.JCheckBox();
        jCBE = new javax.swing.JCheckBox();
        jCBT = new javax.swing.JCheckBox();
        jCBS = new javax.swing.JCheckBox();
        jCBB = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jBConferma = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIModifica = new javax.swing.JMenuItem();
        jMIEsporta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Elenco Pacchetti");

        jFTFNsett.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFTFNsett.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTFNsettKeyReleased(evt);
            }
        });

        jLabel2.setText("Numero Settimana");

        jFTFNsd.setEditable(false);
        jFTFNsd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jBnsdInc.setText("+");
        jBnsdInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnsdIncActionPerformed(evt);
            }
        });

        jBnsdDec.setText("-");
        jBnsdDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnsdDecActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero Stanze Doppie");

        jFTFPsd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFTFPsd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTFPsdKeyReleased(evt);
            }
        });

        jLabel4.setText("Prezzo Stanza Doppia");

        jFTFNsu.setEditable(false);
        jFTFNsu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jBnsuInc.setText("+");
        jBnsuInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnsuIncActionPerformed(evt);
            }
        });

        jBnsuDec.setText("-");
        jBnsuDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnsuDecActionPerformed(evt);
            }
        });

        jLabel5.setText("Numero Stanze  Suite");

        jFTFPsu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFTFPsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTFPsuKeyReleased(evt);
            }
        });

        jLabel6.setText("Prezzo Stanza Suite");

        jCBV.setText("V");

        jCBE.setText("E");

        jCBT.setText("T");

        jCBS.setText("S");

        jCBB.setText("B");

        jLabel7.setText("Corsi");

        jBConferma.setText("Conferma");
        jBConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfermaActionPerformed(evt);
            }
        });

        jMenu1.setText("Gestione Offerta");

        jMIModifica.setText("Modifica");
        jMIModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIModificaActionPerformed(evt);
            }
        });
        jMenu1.add(jMIModifica);

        jMIEsporta.setText("Esporta");
        jMIEsporta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEsportaActionPerformed(evt);
            }
        });
        jMenu1.add(jMIEsporta);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFNsett, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFPsu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFPsd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFTFNsu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBnsuInc)
                        .addGap(10, 10, 10)
                        .addComponent(jBnsuDec))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCBV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBB))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jCmBElenco, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jFTFNsd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBnsdInc)
                            .addGap(10, 10, 10)
                            .addComponent(jBnsdDec))))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(jBConferma)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmBElenco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFNsett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFNsd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnsdInc)
                    .addComponent(jBnsdDec)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFPsd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnsuInc)
                    .addComponent(jBnsuDec)
                    .addComponent(jLabel5)
                    .addComponent(jFTFNsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFPsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCBV)
                    .addComponent(jCBE)
                    .addComponent(jCBS)
                    .addComponent(jCBB)
                    .addComponent(jCBT))
                .addGap(18, 18, 18)
                .addComponent(jBConferma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIModificaActionPerformed
        jBnsdInc.setVisible(true);
        jBnsdDec.setVisible(true);
        jBnsuInc.setVisible(true);
        jBnsuDec.setVisible(true);
        jBConferma.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jCBV.setVisible(true);
        jCBE.setVisible(true);
        jCBT.setVisible(true);
        jCBS.setVisible(true);
        jCBB.setVisible(true);
        jCmBElenco.setVisible(true);
        jFTFNsett.setVisible(true);
        jFTFNsd.setVisible(true);
        jFTFPsd.setVisible(true);
        jFTFNsu.setVisible(true);
        jFTFPsu.setVisible(true);
        String[] s = offermanager.showList();
        for (int i = 0; i < s.length; i++) {
            jCmBElenco.insertItemAt(s[i], i);
        }

    }//GEN-LAST:event_jMIModificaActionPerformed

    private void jFTFNsettKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTFNsettKeyReleased
        int nsett = Integer.parseInt(jFTFNsett.getText());
        if(nsett<1 || nsett>52) jFTFNsett.setText("");
        String nomevillaggio = (String) jCmBElenco.getSelectedItem();
        Settimana settimana = AgenziaSystem.archivio.getPacchetto(nomevillaggio).getSettimana(nsett);
        jFTFNsd.setText(String.valueOf(settimana.getNSD()));
        jFTFPsd.setText(String.valueOf(settimana.getPSD()));
        jFTFNsu.setText(String.valueOf(settimana.getNSU()));
        jFTFPsu.setText(String.valueOf(settimana.getPSU()));
        for (Corso c : settimana.getCorsi()) {
            switch (c) {
                case V:
                     jCBV.setSelected(true);
                    break;
                case E:
                    jCBE.setSelected(true);
                    break;
                case T:
                    jCBT.setSelected(true);
                    break;
                case S:
                    jCBS.setSelected(true);
                    break;
                case B:
                    jCBB.setSelected(true);
                    break;
            }
        }
    }//GEN-LAST:event_jFTFNsettKeyReleased

    private void jBnsdIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnsdIncActionPerformed
        String modifiche="D"+";"+"+";
        String nomevillaggio = (String) jCmBElenco.getSelectedItem();
        int nsd=Integer.parseInt(jFTFNsd.getText())+1;
        int nsett=Integer.parseInt(jFTFNsett.getText());
        try {
            offermanager.modArchive(nomevillaggio, nsett, modifiche);
        } catch (DoubleRoomFullException ex) {
        } catch (SingleRoomFullException ex) {
        }
        jFTFNsd.setText(String.valueOf(nsd));
    }//GEN-LAST:event_jBnsdIncActionPerformed

    private void jBnsdDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnsdDecActionPerformed

        String modifiche="D"+";"+"-";
        String nomevillaggio = (String) jCmBElenco.getSelectedItem();
        int nsd=Integer.parseInt(jFTFNsd.getText())-1;
        int nsett=Integer.parseInt(jFTFNsett.getText());
        try {
            offermanager.modArchive(nomevillaggio, nsett, modifiche);
        } catch (DoubleRoomFullException ex) {
            int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Vuoi spostare la prenotazione in un'altro villagio?", "", JOptionPane.YES_NO_OPTION);
            if(showConfirmDialog==0){
                String showInputDialog = (String) JOptionPane.showInputDialog(rootPane,"Seleziona il villaggio","",JOptionPane.PLAIN_MESSAGE, null, offermanager.showList(), rootPaneCheckingEnabled);
                if(offermanager.movePrenotation(nomevillaggio,showInputDialog, nsett, true, 'D')){
                    JOptionPane.showMessageDialog(rootPane,"Prenotazione Spostata");
                }else
                    JOptionPane.showMessageDialog(rootPane,"Impossibile spostare la prenotazione");
            }
        } catch (SingleRoomFullException ex) {
        }
        jFTFNsd.setText(String.valueOf(nsd));
    }//GEN-LAST:event_jBnsdDecActionPerformed

    private void jFTFPsdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTFPsdKeyReleased
         String modifiche="X"+";"+jFTFPsd.getText();
        String nomevillaggio = (String) jCmBElenco.getSelectedItem();
        int nsett=Integer.parseInt(jFTFNsett.getText());
        try {
            offermanager.modArchive(nomevillaggio, nsett, modifiche);
        } catch (DoubleRoomFullException ex) {
        } catch (SingleRoomFullException ex) {
        }
    }//GEN-LAST:event_jFTFPsdKeyReleased

    private void jBnsuIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnsuIncActionPerformed
       String modifiche="S"+";"+"+";
        String nomevillaggio = (String) jCmBElenco.getSelectedItem();
        int nsu=Integer.parseInt(jFTFNsu.getText())+1;
        int nsett=Integer.parseInt(jFTFNsett.getText());
        try {
            offermanager.modArchive(nomevillaggio, nsett, modifiche);
        } catch (DoubleRoomFullException ex) {
        } catch (SingleRoomFullException ex) {
        }
        jFTFNsu.setText(String.valueOf(nsu));
    }//GEN-LAST:event_jBnsuIncActionPerformed

    private void jBnsuDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnsuDecActionPerformed

        String modifiche="S"+";"+"-";
        String nomevillaggio = (String) jCmBElenco.getSelectedItem();
        int nsu=Integer.parseInt(jFTFNsu.getText())-1;
        int nsett=Integer.parseInt(jFTFNsett.getText());
        try {
            offermanager.modArchive(nomevillaggio, nsett, modifiche);
        } catch (DoubleRoomFullException ex) {
        } catch (SingleRoomFullException ex) {
            int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Vuoi spostare la prenotazione in un'altro villagio?", "", JOptionPane.YES_NO_OPTION);
            if(showConfirmDialog>0){
                 String showInputDialog = (String) JOptionPane.showInputDialog(rootPane,"Seleziona il villaggio","",JOptionPane.PLAIN_MESSAGE, null, offermanager.showList(), rootPaneCheckingEnabled);
                if(offermanager.movePrenotation(nomevillaggio,showInputDialog, nsett, true, 'S')){
                    JOptionPane.showMessageDialog(rootPane,"Prenotazione Spostata");
                }else
                    JOptionPane.showMessageDialog(rootPane,"Impossibile spostare la prenotazione");
            }
        }
        jFTFNsu.setText(String.valueOf(nsu));
    }//GEN-LAST:event_jBnsuDecActionPerformed

    private void jFTFPsuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTFPsuKeyReleased
        String modifiche="Y"+";"+jFTFPsu.getText();
        String nomevillaggio = (String) jCmBElenco.getSelectedItem();
        int nsett=Integer.parseInt(jFTFNsett.getText());
        try {
            offermanager.modArchive(nomevillaggio, nsett, modifiche);
        } catch (DoubleRoomFullException ex) {
        } catch (SingleRoomFullException ex) {
        }
    }//GEN-LAST:event_jFTFPsuKeyReleased

    private void jBConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfermaActionPerformed
       String modifiche="C"+";";
       String nomevillaggio = (String) jCmBElenco.getSelectedItem();
       int nsett=Integer.parseInt(jFTFNsett.getText());
       if(jCBV.isSelected()) modifiche+="V";
       if(jCBE.isSelected()) modifiche+="E";
       if(jCBT.isSelected()) modifiche+="T";
       if(jCBS.isSelected()) modifiche+="S";
       if(jCBB.isSelected()) modifiche+="B";

        try {
            offermanager.modArchive(nomevillaggio, nsett, modifiche);
            JOptionPane.showMessageDialog(rootPane, "Confermato","",JOptionPane.INFORMATION_MESSAGE);
            
        } catch (DoubleRoomFullException ex) {
        } catch (SingleRoomFullException ex) {
        }


    }//GEN-LAST:event_jBConfermaActionPerformed

    private void jMIEsportaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEsportaActionPerformed
        String showInputDialog = JOptionPane.showInputDialog(rootPane, "Nome File","Inserisci Nome File",JOptionPane.OK_CANCEL_OPTION);
        try {
          if(offermanager.exportPrenotation(showInputDialog)){
              JOptionPane.showMessageDialog(rootPane, "Esportazione Effettuate");
          }
        } catch (FileNotFoundException ex) {
        }
    }//GEN-LAST:event_jMIEsportaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Main.gui.setVisible(true);
    }//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConferma;
    private javax.swing.JButton jBnsdDec;
    private javax.swing.JButton jBnsdInc;
    private javax.swing.JButton jBnsuDec;
    private javax.swing.JButton jBnsuInc;
    private javax.swing.JCheckBox jCBB;
    private javax.swing.JCheckBox jCBE;
    private javax.swing.JCheckBox jCBS;
    private javax.swing.JCheckBox jCBT;
    private javax.swing.JCheckBox jCBV;
    private javax.swing.JComboBox jCmBElenco;
    private javax.swing.JFormattedTextField jFTFNsd;
    private javax.swing.JFormattedTextField jFTFNsett;
    private javax.swing.JFormattedTextField jFTFNsu;
    private javax.swing.JFormattedTextField jFTFPsd;
    private javax.swing.JFormattedTextField jFTFPsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMIEsporta;
    private javax.swing.JMenuItem jMIModifica;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
